version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: panconnect_postgres_stage
    restart: always
    environment:
      POSTGRES_USER: Meghraj
      POSTGRES_PASSWORD: Monya848
      POSTGRES_DB: panconnect_stage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: